name: navigation_assistant
description: "Навигационный помощник для слабовидящих"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'  # Более гибкая версия SDK

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  tflite_flutter: ^0.12.0  # Совм
  wakelock_plus: ^1.4.0
  image: ^3.2.1  # Более старая версия для совместимости
  flutter_tts: ^3.8.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/yolov5s.tflite